In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = "/home/skand/Workspace/MIT/analytics_edge/Analytics_Edge_Tennis_prediction"
os.chdir(path)
print(os.path.abspath(os.curdir))

/home/skand/Workspace/MIT/analytics_edge/Analytics_Edge_Tennis_prediction

In [8]:
def replace_spaces_dashes(x):
    x = str(x).replace(" ","")
    x = x.replace("_","")
    return x

'aze'

In [58]:
odds = pd.DataFrame()
for year in range (2001,2021):
    df_date = pd.read_csv('odds_data/raw_odds/'+str(year)+'.csv')
    odds = pd.concat([odds,df_date],sort=False,ignore_index=True)
    
odds['Date'] = pd.to_datetime(odds['Date'])
odds['year'] = odds['Date'].dt.year
odds['Date']=odds['Date'].apply(lambda x:x.strftime('%Y-%m-%d'))

odds['winner_unique_id']=odds['Winner'].apply(lambda x:replace_spaces_dashes(x).lower())+'//'+odds['year'].apply(lambda x:str(x))
odds['loser_unique_id']=odds['Loser'].apply(lambda x:replace_spaces_dashes(x).lower())+'//'+odds['year'].apply(lambda x:str(x))
odds['game_unique_id']=odds['winner_unique_id']+odds['loser_unique_id']
odds

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,SJW,SJL,MaxW,MaxL,AvgW,AvgL,year,winner_unique_id,loser_unique_id,game_unique_id
0,1.0,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Clement A.,...,NaN,NaN,NaN,NaN,NaN,NaN,2001,clementa.//2001,gaudenzia.//2001,clementa.//2001gaudenzia.//2001
1,1.0,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Goldstein P.,...,NaN,NaN,NaN,NaN,NaN,NaN,2001,goldsteinp.//2001,jonesa.//2001,goldsteinp.//2001jonesa.//2001
2,1.0,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Haas T.,...,NaN,NaN,NaN,NaN,NaN,NaN,2001,haast.//2001,smithl.//2001,haast.//2001smithl.//2001
3,1.0,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Henman T.,...,NaN,NaN,NaN,NaN,NaN,NaN,2001,henmant.//2001,rusedskig.//2001,henmant.//2001rusedskig.//2001
4,1.0,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Hewitt L.,...,NaN,NaN,NaN,NaN,NaN,NaN,2001,hewittl.//2001,arthursw.//2001,hewittl.//2001arthursw.//2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52786,21.0,Hamburg,German Tennis Championships,2020-09-25,ATP500,Outdoor,Clay,Quarterfinals,3.0,Ruud C.,...,NaN,NaN,1.48,3.58,1.37,3.09,2020,ruudc.//2020,humbertu.//2020,ruudc.//2020humbertu.//2020
52787,21.0,Hamburg,German Tennis Championships,2020-09-25,ATP500,Outdoor,Clay,Quarterfinals,3.0,Garin C.,...,NaN,NaN,1.36,3.70,1.31,3.48,2020,garinc.//2020,bublika.//2020,garinc.//2020bublika.//2020
52788,21.0,Hamburg,German Tennis Championships,2020-09-26,ATP500,Outdoor,Clay,Semifinals,3.0,Rublev A.,...,NaN,NaN,1.51,3.00,1.46,2.71,2020,rubleva.//2020,ruudc.//2020,rubleva.//2020ruudc.//2020
52789,21.0,Hamburg,German Tennis Championships,2020-09-26,ATP500,Outdoor,Clay,Semifinals,3.0,Tsitsipas S.,...,NaN,NaN,1.34,4.12,1.30,3.57,2020,tsitsipass.//2020,garinc.//2020,tsitsipass.//2020garinc.//2020
52790,21.0,Hamburg,German Tennis Championships,2020-09-27,ATP500,Outdoor,Clay,The Final,3.0,Rublev A.,...,NaN,NaN,1.90,2.16,1.77,2.06,2020,rubleva.//2020,tsitsipass.//2020,rubleva.//2020tsitsipass.//2020

In [53]:
games=pd.read_csv('jean_work/processed_data/dataset_v1.csv')
games['winner_unique_id']=games['winner'].apply(lambda x:replace_spaces_dashes(x))+'//'+games['year'].apply(lambda x:str(x))
games['loser_unique_id']=games['loser'].apply(lambda x:replace_spaces_dashes(x))+'//'+games['year'].apply(lambda x:str(x))
games['game_unique_id']=games['winner_unique_id']+games['loser_unique_id']
games = games[games['year']>2000]
games

,year,week_title,round,winner,loser,court,surface,tourney_singles_draw,wrank,lrank,...,winner_games_before,loser_games_before,winner_age,loser_age,winner_year_pro,loser_year_pro,winner_player,winner_unique_id,loser_unique_id,game_unique_id
35766,2001,2001-01-01,1.0,haas_t.,massu_n.,Outdoor,Hard,32,23.0,87.0,...,85.0,97.0,8309 days,7754 days,5.0,4.0,1,haast.//2001,massun.//2001,haast.//2001massun.//2001
35767,2001,2001-01-01,2.0,massu_n.,henman_t.,Outdoor,Hard,32,87.0,10.0,...,68.0,73.0,7754 days,9614 days,4.0,8.0,1,massun.//2001,henmant.//2001,massun.//2001henmant.//2001
35768,2001,2001-01-01,2.0,haas_t.,stoltenberg_j.,Outdoor,Hard,32,23.0,66.0,...,62.0,52.0,8309 days,11230 days,5.0,14.0,1,haast.//2001,stoltenbergj.//2001,haast.//2001stoltenbergj.//2001
35769,2001,2001-01-01,3.0,hewitt_l.,haas_t.,Outdoor,Hard,32,7.0,23.0,...,48.0,39.0,7251 days,8309 days,3.0,5.0,0,hewittl.//2001,haast.//2001,hewittl.//2001haast.//2001
35770,2001,2001-01-01,3.0,henman_t.,johansson_t.,Outdoor,Hard,32,10.0,39.0,...,38.0,42.0,9614 days,9415 days,8.0,7.0,1,henmant.//2001,johanssont.//2001,henmant.//2001johanssont.//2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106685,2020,2020-02-27,3.0,wawrinka_s.,dimitrov_g.,Outdoor,Hard,32,16.0,22.0,...,0.0,0.0,12754 days,10514 days,18.0,12.0,0,wawrinkas.//2020,dimitrovg.//2020,wawrinkas.//2020dimitrovg.//2020
106686,2020,2020-02-27,3.0,nadal_r.,kwon_s.w.,Outdoor,Hard,32,2.0,76.0,...,34.0,0.0,12322 days,NaN,19.0,NaN,1,nadalr.//2020,kwons.w.//2020,nadalr.//2020kwons.w.//2020
106687,2020,2020-02-27,2.0,isner_j.,fritz_t.,Outdoor,Hard,32,20.0,35.0,...,0.0,0.0,12725 days,8157 days,13.0,5.0,0,isnerj.//2020,fritzt.//2020,isnerj.//2020fritzt.//2020
106688,2020,2020-02-27,2.0,nadal_r.,dimitrov_g.,Outdoor,Hard,32,2.0,22.0,...,17.0,0.0,12322 days,10514 days,19.0,12.0,1,nadalr.//2020,dimitrovg.//2020,nadalr.//2020dimitrovg.//2020
106689,2020,2020-02-27,1.0,fritz_t.,nadal_r.,Outdoor,Hard,32,35.0,2.0,...,0.0,0.0,8157 days,12322 days,5.0,19.0,0,fritzt.//2020,nadalr.//2020,fritzt.//2020nadalr.//2020

In [59]:
len(games["game_unique_id"].unique())
len(odds["game_unique_id"].unique())

47874

In [60]:
gamesUnique = np.sort(games.game_unique_id.unique())
oddsUnique = np.sort(odds.game_unique_id.unique())
intersect = np.sort(np.intersect1d(gamesUnique,oddsUnique))
notInOdds = gamesUnique[~np.isin(gamesUnique,intersect)]
notInGames = oddsUnique[~np.isin(oddsUnique,intersect)]

In [63]:
games[games["game_unique_id"] == "zverevm.//2019nadalr.//2019"]

,year,week_title,round,winner,loser,court,surface,tourney_singles_draw,wrank,lrank,...,winner_games_before,loser_games_before,winner_age,loser_age,winner_year_pro,loser_year_pro,winner_player,winner_unique_id,loser_unique_id,game_unique_id
104569,2019,2019-02-27,5.0,zverev_m.,nadal_r.,Outdoor,Hard,32,76.0,2.0,...,0.0,0.0,11512 days,11957 days,14.0,18.0,0,zverevm.//2019,nadalr.//2019,zverevm.//2019nadalr.//2019

In [70]:
odds[odds["winner_unique_id"] == "zverevm.//2019"]

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,SJW,SJL,MaxW,MaxL,AvgW,AvgL,year,winner_unique_id,loser_unique_id,game_unique_id
50044,20.0,Miami,Sony Ericsson Open,2019-03-20,Masters 1000,Outdoor,Hard,1st Round,3.0,Zverev M.,...,NaN,NaN,2.12,1.87,2.05,1.78,2019,zverevm.//2019,kuhnn.//2019,zverevm.//2019kuhnn.//2019
51002,41.0,Newport,Hall of Fame Championships,2019-07-16,ATP250,Outdoor,Grass,1st Round,3.0,Zverev M.,...,NaN,NaN,2.75,1.66,2.41,1.56,2019,zverevm.//2019,smyczekt.//2019,zverevm.//2019smyczekt.//2019
51008,41.0,Newport,Hall of Fame Championships,2019-07-17,ATP250,Outdoor,Grass,2nd Round,3.0,Zverev M.,...,NaN,NaN,1.87,2.09,1.78,2.03,2019,zverevm.//2019,andreozzig.//2019,zverevm.//2019andreozzig.//2019

In [42]:
games[games["game_unique_id"].isin(notInOdds)]

,year,week_title,round,winner,loser,court,surface,tourney_singles_draw,wrank,lrank,...,winner_games_before,loser_games_before,winner_age,loser_age,winner_year_pro,loser_year_pro,winner_player,winner_unique_id,loser_unique_id,game_unique_id
35769,2001,2001-01-01,3.0,hewitt_l.,haas_t.,Outdoor,Hard,32,7.0,23.0,...,48.0,39.0,7251 days,8309 days,3.0,5.0,0,hewittl.//2001-01-01,haast.//2001-01-01,hewittl.//2001-01-01haast.//2001-01-01
35772,2001,2001-01-01,3.0,martin_a.,stoltenberg_j.,Outdoor,Hard,32,579.0,66.0,...,51.0,33.0,8170 days,11230 days,6.0,14.0,0,martina.//2001-01-01,stoltenbergj.//2001-01-01,martina.//2001-01-01stoltenbergj.//2001-01-01
35775,2001,2001-01-01,4.0,clement_a.,massu_n.,Outdoor,Hard,32,18.0,87.0,...,28.0,18.0,8416 days,7754 days,5.0,4.0,0,clementa.//2001-01-01,massun.//2001-01-01,clementa.//2001-01-01massun.//2001-01-01
35776,2001,2001-01-01,4.0,malisse_x.,haas_t.,Outdoor,Hard,32,127.0,23.0,...,25.0,18.0,7471 days,8309 days,3.0,5.0,0,malissex.//2001-01-01,haast.//2001-01-01,malissex.//2001-01-01haast.//2001-01-01
35778,2001,2001-01-01,4.0,vinck_c.,johansson_t.,Outdoor,Hard,32,102.0,39.0,...,23.0,21.0,9252 days,9415 days,8.0,7.0,0,vinckc.//2001-01-01,johanssont.//2001-01-01,vinckc.//2001-01-01johanssont.//2001-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106685,2020,2020-02-27,3.0,wawrinka_s.,dimitrov_g.,Outdoor,Hard,32,16.0,22.0,...,0.0,0.0,12754 days,10514 days,18.0,12.0,0,wawrinkas.//2020-02-27,dimitrovg.//2020-02-27,wawrinkas.//2020-02-27dimitrovg.//2020-02-27
106686,2020,2020-02-27,3.0,nadal_r.,kwon_s.w.,Outdoor,Hard,32,2.0,76.0,...,34.0,0.0,12322 days,NaN,19.0,NaN,1,nadalr.//2020-02-27,kwons.w.//2020-02-27,nadalr.//2020-02-27kwons.w.//2020-02-27
106687,2020,2020-02-27,2.0,isner_j.,fritz_t.,Outdoor,Hard,32,20.0,35.0,...,0.0,0.0,12725 days,8157 days,13.0,5.0,0,isnerj.//2020-02-27,fritzt.//2020-02-27,isnerj.//2020-02-27fritzt.//2020-02-27
106688,2020,2020-02-27,2.0,nadal_r.,dimitrov_g.,Outdoor,Hard,32,2.0,22.0,...,17.0,0.0,12322 days,10514 days,19.0,12.0,1,nadalr.//2020-02-27,dimitrovg.//2020-02-27,nadalr.//2020-02-27dimitrovg.//2020-02-27
106689,2020,2020-02-27,1.0,fritz_t.,nadal_r.,Outdoor,Hard,32,35.0,2.0,...,0.0,0.0,8157 days,12322 days,5.0,19.0,0,fritzt.//2020-02-27,nadalr.//2020-02-27,fritzt.//2020-02-27nadalr.//2020-02-27

In [50]:
games.columns

Index(['year', 'week_title', 'round', 'winner', 'loser', 'court', 'surface',
       'tourney_singles_draw', 'wrank', 'lrank', 'wpts', 'lpts', 'wrank_avg',
       'lrank_avg', 'wpts_avg', 'lpts_avg', 'winner_percentage_aces',
       'winner_percentage_df', 'winner_percentage_1stwon',
       'winner_percentage_bpsaved', 'winner_percentage_bpobtained',
       'winner_percentage_bpconverted', 'loser_percentage_aces',
       'loser_percentage_df', 'loser_percentage_1stwon',
       'loser_percentage_bpsaved', 'loser_percentage_bpobtained',
       'loser_percentage_bpconverted', 'winner_weight_kg', 'loser_weight_kg',
       'winner_height_cm', 'loser_height_cm', 'winner_handedness',
       'loser_handedness', 'winner_backhand', 'loser_backhand',
       'winner_games_before', 'loser_games_before', 'winner_age', 'loser_age',
       'winner_year_pro', 'loser_year_pro', 'winner_player',
       'winner_unique_id', 'loser_unique_id', 'game_unique_id'],
      dtype='object')

In [51]:
odds.columns

Index(['ATP', 'Location', 'Tournament', 'Date', 'Series', 'Court', 'Surface',
       'Round', 'Best of', 'Winner', 'Loser', 'WRank', 'LRank', 'W1', 'L1',
       'W2', 'L2', 'W3', 'L3', 'W4', 'L4', 'W5', 'L5', 'Wsets', 'Lsets',
       'Comment', 'CBW', 'CBL', 'GBW', 'GBL', 'IWW', 'IWL', 'SBW', 'SBL',
       'B365W', 'B365L', 'B&WW', 'B&WL', 'EXW', 'EXL', 'PSW', 'PSL', 'WPts',
       'LPts', 'UBW', 'UBL', 'LBW', 'LBL', 'SJW', 'SJL', 'MaxW', 'MaxL',
       'AvgW', 'AvgL', 'winner_unique_id', 'loser_unique_id',
       'game_unique_id'],
      dtype='object')

In [49]:
len(odds["Date"].unique())
np.sort(games["week_title"].unique())

array(['2001-01-01', '2001-01-08', '2001-01-15', '2001-01-28',
       '2001-01-29', '2001-02-12', '2001-02-19', '2001-02-26',
       '2001-03-05', '2001-03-12', '2001-03-19', '2001-04-09',
       '2001-04-16', '2001-04-23', '2001-04-30', '2001-05-07',
       '2001-05-14', '2001-05-21', '2001-05-28', '2001-06-11',
       '2001-06-18', '2001-06-25', '2001-07-09', '2001-07-16',
       '2001-07-23', '2001-07-30', '2001-08-06', '2001-08-13',
       '2001-08-20', '2001-08-27', '2001-09-10', '2001-09-17',
       '2001-09-24', '2001-10-01', '2001-10-08', '2001-10-15',
       '2001-10-22', '2001-10-29', '2001-11-12', '2002-01-07',
       '2002-01-14', '2002-01-28', '2002-02-11', '2002-02-18',
       '2002-02-25', '2002-03-04', '2002-03-11', '2002-03-18',
       '2002-04-08', '2002-04-15', '2002-04-22', '2002-04-29',
       '2002-05-06', '2002-05-13', '2002-05-20', '2002-05-27',
       '2002-06-10', '2002-06-17', '2002-06-24', '2002-07-08',
       '2002-07-15', '2002-07-22', '2002-07-29', '2002-08-05',
       '2002-08-12', '2002-08-19', '2002-08-26', '2002-09-09',
       '2002-09-23', '2002-09-30', '2002-10-07', '2002-10-14',
       '2002-10-21', '2002-10-28', '2002-11-11', '2003-01-06',
       '2003-01-13', '2003-01-27', '2003-02-10', '2003-02-17',
       '2003-02-24', '2003-03-03', '2003-03-10', '2003-03-17',
       '2003-04-07', '2003-04-14', '2003-04-21', '2003-04-28',
       '2003-05-05', '2003-05-12', '2003-05-19', '2003-05-26',
       '2003-06-09', '2003-06-16', '2003-06-23', '2003-07-07',
       '2003-07-14', '2003-07-21', '2003-07-28', '2003-08-04',
       '2003-08-11', '2003-08-18', '2003-08-25', '2003-09-08',
       '2003-09-22', '2003-09-29', '2003-10-06', '2003-10-13',
       '2003-10-20', '2003-10-27', '2003-11-10', '2004-01-05',
       '2004-01-12', '2004-01-19', '2004-02-09', '2004-02-16',
       '2004-02-23', '2004-03-01', '2004-03-08', '2004-03-22',
       '2004-04-12', '2004-04-19', '2004-04-26', '2004-05-03',
       '2004-05-10', '2004-05-17', '2004-05-24', '2004-06-07',
       '2004-06-14', '2004-06-21', '2004-07-05', '2004-07-12',
       '2004-07-19', '2004-07-26', '2004-08-02', '2004-08-09',
       '2004-08-16', '2004-08-23', '2004-08-30', '2004-09-13',
       '2004-09-27', '2004-10-04', '2004-10-11', '2004-10-18',
       '2004-10-25', '2004-11-01', '2004-11-15', '2005-01-03',
       '2005-01-10', '2005-01-17', '2005-01-31', '2005-02-07',
       '2005-02-14', '2005-02-21', '2005-03-07', '2005-03-21',
       '2005-04-04', '2005-04-11', '2005-04-18', '2005-04-25',
       '2005-05-02', '2005-05-09', '2005-05-16', '2005-05-23',
       '2005-06-06', '2005-06-13', '2005-06-20', '2005-07-04',
       '2005-07-18', '2005-07-25', '2005-08-01', '2005-08-08',
       '2005-08-15', '2005-08-22', '2005-08-29', '2005-09-12',
       '2005-09-26', '2005-10-03', '2005-10-10', '2005-10-17',
       '2005-10-24', '2005-10-31', '2005-11-14', '2006-01-02',
       '2006-01-09', '2006-01-16', '2006-01-30', '2006-02-13',
       '2006-02-20', '2006-02-27', '2006-03-06', '2006-03-20',
       '2006-04-10', '2006-04-17', '2006-04-24', '2006-05-01',
       '2006-05-08', '2006-05-15', '2006-05-22', '2006-05-29',
       '2006-06-12', '2006-06-19', '2006-06-26', '2006-07-10',
       '2006-07-17', '2006-07-24', '2006-07-31', '2006-08-07',
       '2006-08-14', '2006-08-21', '2006-08-28', '2006-09-11',
       '2006-09-25', '2006-10-02', '2006-10-09', '2006-10-16',
       '2006-10-23', '2006-10-30', '2006-11-13', '2007-01-01',
       '2007-01-08', '2007-01-15', '2007-01-28', '2007-01-29',
       '2007-02-12', '2007-02-19', '2007-02-26', '2007-03-05',
       '2007-03-19', '2007-04-09', '2007-04-15', '2007-04-23',
       '2007-04-29', '2007-04-30', '2007-05-07', '2007-05-14',
       '2007-05-20', '2007-05-28', '2007-06-11', '2007-06-17',
       '2007-06-18', '2007-06-25', '2007-07-09', '2007-07-16',
       '2007-07-23', '2007-07-29', '2007-07-30', '2007-08-05',
       '2007-08-13', '2007-08-19', '2007-08-27', '2007-09-10',
       '2007-09-24', '2007-10-01', '2007-10-07', '2007-10-08',
       '2007-10-15', '2007-10-22', '2007-10-28', '2007-11-12',
       '2008-01-07', '2008-01-14', '2008-01-28', '2008-02-11',
       '2008-02-18', '2008-02-25', '2008-03-03', '2008-03-13',
       '2008-03-27', '2008-04-14', '2008-04-20', '2008-04-28',
       '2008-05-05', '2008-05-11', '2008-05-18', '2008-05-25',
       '2008-06-09', '2008-06-15', '2008-06-16', '2008-06-23',
       '2008-07-07', '2008-07-14', '2008-07-21', '2008-07-28',
       '2008-08-04', '2008-08-10', '2008-08-11', '2008-08-17',
       '2008-08-25', '2008-09-08', '2008-09-22', '2008-09-29',
       '2008-10-06', '2008-10-12', '2008-10-20', '2008-10-26',
       '2008-11-09', '2009-01-04', '2009-01-05', '2009-01-12',
       '2009-01-19', '2009-02-02', '2009-02-09', '2009-02-16',
       '2009-02-23', '2009-03-12', '2009-03-25', '2009-04-06',
       '2009-04-12', '2009-04-20', '2009-04-27', '2009-05-03',
       '2009-05-04', '2009-05-10', '2009-05-17', '2009-05-25',
       '2009-06-08', '2009-06-14', '2009-06-22', '2009-07-06',
       '2009-07-13', '2009-07-19', '2009-07-26', '2009-07-27',
       '2009-08-02', '2009-08-10', '2009-08-16', '2009-08-23',
       '2009-08-31', '2009-09-21', '2009-09-28', '2009-10-05',
       '2009-10-11', '2009-10-19', '2009-10-25', '2009-10-26',
       '2009-11-02', '2009-11-08', '2009-11-22', '2010-01-03',
       '2010-01-04', '2010-01-11', '2010-01-18', '2010-02-01',
       '2010-02-08', '2010-02-15', '2010-02-22', '2010-03-11',
       '2010-03-24', '2010-04-05', '2010-04-11', '2010-04-19',
       '2010-04-25', '2010-05-02', '2010-05-03', '2010-05-09',
       '2010-05-16', '2010-05-24', '2010-06-07', '2010-06-13',
       '2010-06-21', '2010-07-05', '2010-07-12', '2010-07-19',
       '2010-07-25', '2010-07-26', '2010-08-01', '2010-08-09',
       '2010-08-15', '2010-08-22', '2010-08-30', '2010-09-20',
       '2010-09-27', '2010-10-04', '2010-10-10', '2010-10-18',
       '2010-10-25', '2010-10-31', '2010-11-01', '2010-11-07',
       '2010-11-21', '2011-01-02', '2011-01-03', '2011-01-10',
       '2011-01-17', '2011-01-31', '2011-02-07', '2011-02-14',
       '2011-02-21', '2011-03-10', '2011-03-23', '2011-04-04',
       '2011-04-10', '2011-04-18', '2011-04-24', '2011-04-25',
       '2011-05-01', '2011-05-08', '2011-05-15', '2011-05-22',
       '2011-06-06', '2011-06-12', '2011-06-20', '2011-07-04',
       '2011-07-11', '2011-07-18', '2011-07-25', '2011-07-31',
       '2011-08-08', '2011-08-14', '2011-08-21', '2011-08-29',
       '2011-09-19', '2011-09-26', '2011-10-03', '2011-10-09',
       '2011-10-17', '2011-10-24', '2011-10-31', '2011-11-07',
       '2011-11-20', '2012-01-01', '2012-01-02', '2012-01-09',
       '2012-01-16', '2012-01-30', '2012-02-13', '2012-02-20',
       '2012-02-27', '2012-03-08', '2012-03-21', '2012-04-09',
       '2012-04-15', '2012-04-23', '2012-04-30', '2012-05-06',
       '2012-05-13', '2012-05-20', '2012-05-27', '2012-06-11',
       '2012-06-17', '2012-06-18', '2012-06-25', '2012-07-09',
       '2012-07-16', '2012-07-22', '2012-07-23', '2012-07-25',
       '2012-07-30', '2012-08-06', '2012-08-12', '2012-08-19',
       '2012-08-27', '2012-09-17', '2012-09-24', '2012-10-01',
       '2012-10-07', '2012-10-15', '2012-10-21', '2012-10-22',
       '2012-10-29', '2012-11-05', '2013-01-07', '2013-01-14',
       '2013-02-04', '2013-02-11', '2013-02-18', '2013-02-25',
       '2013-03-07', '2013-03-20', '2013-04-08', '2013-04-14',
       '2013-04-22', '2013-04-29', '2013-05-05', '2013-05-12',
       '2013-05-19', '2013-05-27', '2013-06-10', '2013-06-16',
       '2013-06-17', '2013-06-24', '2013-07-08', '2013-07-15',
       '2013-07-22', '2013-07-28', '2013-07-29', '2013-08-05',
       '2013-08-11', '2013-08-18', '2013-08-26', '2013-09-16',
       '2013-09-23', '2013-09-30', '2013-10-07', '2013-10-14',
       '2013-10-21', '2013-10-28', '2013-11-04', '2014-01-06',
       '2014-01-13', '2014-02-03', '2014-02-10', '2014-02-17',
       '2014-02-24', '2014-03-06', '2014-03-19', '2014-04-07',
       '2014-04-13', '2014-04-21', '2014-04-28', '2014-05-04',
       '2014-05-11', '2014-05-18', '2014-05-26', '2014-06-09',
       '2014-06-15', '2014-06-16', '2014-06-23', '2014-07-07',
       '2014-07-14', '2014-07-21', '2014-07-27', '2014-07-28',
       '2014-08-04', '2014-08-10', '2014-08-17', '2014-08-25',
       '2014-09-15', '2014-09-22', '2014-09-29', '2014-10-05',
       '2014-10-13', '2014-10-20', '2014-10-27', '2014-11-09',
       '2015-01-04', '2015-01-05', '2015-01-11', '2015-01-12',
       '2015-01-19', '2015-02-02', '2015-02-09', '2015-02-16',
       '2015-02-23', '2015-03-12', '2015-03-25', '2015-04-06',
       '2015-04-12', '2015-04-20', '2015-04-27', '2015-05-03',
       '2015-05-10', '2015-05-17', '2015-05-24', '2015-06-08',
       '2015-06-15', '2015-06-21', '2015-06-29', '2015-07-13',
       '2015-07-20', '2015-07-27', '2015-08-03', '2015-08-10',
       '2015-08-16', '2015-08-23', '2015-08-31', '2015-09-21',
       '2015-09-28', '2015-10-05', '2015-10-11', '2015-10-19',
       '2015-10-26', '2015-11-02', '2015-11-15', '2016-01-04',
       '2016-01-11', '2016-01-18', '2016-02-01', '2016-02-08',
       '2016-02-15', '2016-02-22', '2016-03-10', '2016-03-23',
       '2016-04-04', '2016-04-10', '2016-04-18', '2016-04-25',
       '2016-05-01', '2016-05-08', '2016-05-15', '2016-05-22',
       '2016-06-06', '2016-06-13', '2016-06-19', '2016-06-27',
       '2016-07-11', '2016-07-18', '2016-07-25', '2016-08-01',
       '2016-08-04', '2016-08-08', '2016-08-14', '2016-08-21',
       '2016-08-29', '2016-09-19', '2016-09-26', '2016-10-03',
       '2016-10-09', '2016-10-17', '2016-10-24', '2016-10-31',
       '2016-11-13', '2017-01-01', '2017-01-02', '2017-01-08',
       '2017-01-09', '2017-01-16', '2017-02-06', '2017-02-13',
       '2017-02-20', '2017-02-27', '2017-03-09', '2017-03-22',
       '2017-04-10', '2017-04-16', '2017-04-24', '2017-05-01',
       '2017-05-07', '2017-05-14', '2017-05-21', '2017-05-28',
       '2017-06-12', '2017-06-19', '2017-06-25', '2017-06-26',
       '2017-07-03', '2017-07-17', '2017-07-24', '2017-07-31',
       '2017-08-07', '2017-08-13', '2017-08-20', '2017-08-28',
       '2017-09-18', '2017-09-25', '2017-10-02', '2017-10-08',
       '2017-10-16', '2017-10-23', '2017-10-30', '2017-11-12',
       '2018-01-01', '2018-01-02', '2018-01-08', '2018-01-09',
       '2018-01-16', '2018-02-06', '2018-02-13', '2018-02-20',
       '2018-02-27', '2018-03-09', '2018-03-22', '2018-04-10',
       '2018-04-16', '2018-04-24', '2018-05-01', '2018-05-07',
       '2018-05-14', '2018-05-21', '2018-05-28', '2018-06-12',
       '2018-06-19', '2018-06-25', '2018-06-26', '2018-07-17',
       '2018-07-24', '2018-07-31', '2018-08-13', '2018-08-20',
       '2018-08-28', '2018-09-18', '2018-09-25', '2018-10-02',
       '2018-10-08', '2018-10-16', '2018-10-23', '2018-10-30',
       '2018-11-12', '2019-01-01', '2019-01-02', '2019-01-08',
       '2019-01-09', '2019-01-16', '2019-02-06', '2019-02-13',
       '2019-02-20', '2019-02-27', '2019-03-09', '2019-03-22',
       '2019-04-10', '2019-04-16', '2019-04-24', '2019-05-01',
       '2019-05-07', '2019-05-14', '2019-05-21', '2019-05-28',
       '2019-06-12', '2019-06-19', '2019-06-25', '2019-06-26',
       '2019-07-17', '2019-07-24', '2019-07-31', '2019-08-07',
       '2019-08-13', '2019-08-20', '2019-08-28', '2019-09-18',
       '2019-09-25', '2019-10-02', '2019-10-08', '2019-10-16',
       '2019-10-23', '2019-10-30', '2019-11-12', '2020-01-02',
       '2020-01-09', '2020-01-16', '2020-02-06', '2020-02-13',
       '2020-02-20', '2020-02-27', '2020-08-27'], dtype=object)

In [71]:
pd.merge(games,odds,on='game_unique_id')

,year_x,week_title,round,winner,loser,court,surface,tourney_singles_draw,wrank,lrank,...,LBL,SJW,SJL,MaxW,MaxL,AvgW,AvgL,year_y,winner_unique_id_y,loser_unique_id_y
0,2001,2001-01-01,1.0,haas_t.,massu_n.,Outdoor,Hard,32,23.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,haast.//2001,massun.//2001
1,2001,2001-01-01,1.0,haas_t.,massu_n.,Outdoor,Hard,32,23.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,haast.//2001,massun.//2001
2,2001,2001-01-15,7.0,haas_t.,massu_n.,Outdoor,Hard,128,20.0,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,haast.//2001,massun.//2001
3,2001,2001-01-15,7.0,haas_t.,massu_n.,Outdoor,Hard,128,20.0,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,haast.//2001,massun.//2001
4,2001,2001-01-01,2.0,massu_n.,henman_t.,Outdoor,Hard,32,87.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,massun.//2001,henmant.//2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31560,2020,2020-02-27,4.0,nadal_r.,kecmanovic_m.,Outdoor,Hard,32,2.0,50.0,...,NaN,NaN,NaN,1.09,10.20,1.07,8.34,2020,nadalr.//2020,kecmanovicm.//2020
31561,2020,2020-02-27,3.0,isner_j.,paul_t.,Outdoor,Hard,32,20.0,66.0,...,NaN,NaN,NaN,1.80,2.20,1.73,2.10,2020,isnerj.//2020,pault.//2020
31562,2020,2020-02-27,3.0,fritz_t.,edmund_k.,Outdoor,Hard,32,35.0,44.0,...,NaN,NaN,NaN,2.40,1.67,2.30,1.61,2020,fritzt.//2020,edmundk.//2020
31563,2020,2020-02-27,3.0,nadal_r.,kwon_s.w.,Outdoor,Hard,32,2.0,76.0,...,NaN,NaN,NaN,1.07,17.14,1.04,10.94,2020,nadalr.//2020,kwons.w.//2020
31564,2020,2020-02-27,2.0,nadal_r.,dimitrov_g.,Outdoor,Hard,32,2.0,22.0,...,NaN,NaN,NaN,1.15,7.20,1.12,6.29,2020,nadalr.//2020,dimitrovg.//2020